# 名称，显示在Actions列表里的
name: Auto-transport HLAE

# 触发条件
on:
  # 定时 每5分钟触发一次（实际7~8分钟触发一次）
  schedule:
    - cron:  '*/5 * * * *'

# 任务/工作
jobs:
  # Json解析
  parseJson:
    
    # 运行在ubuntu(linux)最新版
    runs-on: ubuntu-latest
    
    # 输出附件assets矩阵给dealWithAssets任务分别处理
    outputs:
      assets: ${{ steps.latest-hlae.outputs.assets }}
      latest: ${{ steps.isLatest.outputs.latest }}

    # 步骤
    steps:
    
    # 1.切换到仓库的目录/工作区
    - uses: actions/checkout@v2
    
    # 2.利用API GET仓库最新发布信息的Json
    - id: request
      uses: octokit/request-action@v2.x
      with:
         route: GET /repos/:owner/:repo/releases/latest
         owner: advancedfx
         repo: advancedfx
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    # 3.处理结果
    - id: result
      uses: gr2m/get-json-paths-action@v1.x
      with:
          json: ${{ steps.request.outputs.data }}
          name: "name"
          tag_name: "tag_name"
          assets: "assets"
    # 4.打印发布信息标题和版本号
    - run: |
          echo "latest release name: ${{ steps.result.outputs.name }}"
          echo "tag_name | Version: (${{ steps.result.outputs.tag_name }})"
          echo "${{ steps.result.outputs.assets }}"
