name: Auto Transport HLAE Latest Assets and Create Release

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  transport:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Get Latest HLAE Tag
      uses: actions-hub/watch-tag@master
      with:
         provider: github
         repository: advancedfx/advancedfx
         env_name:	LATEST_HLAE_TAG
    - name: Get Latest HLAE-Release Tag
      uses: actions-hub/watch-tag@master
      with:
         provider: github
         repository: Purple-CSGO/HLAE-Release
         env_name:	THIS_TAG
    - name: Test Latest HLAE Tag
      run: |
         echo $LATEST_HLAE_TAG
         echo $THIS_TAG
    - if: env.THIS_TAG != env.LATEST_HLAE_TAG
      name: Download Release Asset
      uses: i3h/download-release-asset@v1
      with:
       owner: advancedfx
       repo: advancedfx
       tag: latest
       file: /[A-z0-9]+.zip$/
    - if: env.THIS_TAG != env.LATEST_HLAE_TAG
      name: Push changes
      uses: actions-go/push@v1
    - if: env.THIS_TAG != env.LATEST_HLAE_TAG
      name: Create a Release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
       tag_name: v$LATEST_HLAE_TAG
       release_name: v$LATEST_HLAE_TAG
       body: This release is automatically made by GitHub Actions
       draft: false
       prerelease: false
